name: Run AstroBuild Script

on: [push, pull_request]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Clone AstroBuild repository
      uses: actions/checkout@v4
      with:
        sparse-checkout: .
        repository: aequitas/AstroBuild
        path: astrobuild_repo

    - name: Set up Python 2.7
      uses: actions/setup-python@v4
      with:
        python-version: '2.7'

    - name: Run astro_build.py
      run: python astrobuild_repo/astro_build.py
