name: Run AstroBuild Script

on: [push, pull_request]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clone AstroBuild repository
      run: |
        git clone --depth=1 https://github.com/christian-s/AstroBuild.git astrobuild_repo

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Run astro_build.py
      run: python astrobuild_repo/astro_build.py
